import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * La sidebar des cours est auto-générée à partir de l'arborescence `docs/`.
 *
 * Convention :
 * - `docs/intro.md` est la page d'accueil des cours.
 * - Chaque module est un dossier `module-N-slug/` avec un `_category_.json`
 *   définissant son libellé et son ordre.
 * - Chaque chapitre est un fichier `.md` ou `.mdx` au format défini dans
 *   `docs/charte-redaction.md` (section 6).
 */
const sidebars: SidebarsConfig = {
  coursSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
